package com.inventory.system.model;
// Generated Jun 11, 2016 9:48:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 *AcademicClasss generated by hbm2java
 */
@Entity
@Table(name="academicclass"
    ,catalog="collegestudents"
)
public class AcademicClass  implements java.io.Serializable {


     private Integer id;
     private String className;
     private Set studentRegistrations = new HashSet(0);
     private Set teachers = new HashSet(0);
     private Set studentses = new HashSet(0);
     private Set subjectses = new HashSet(0);
     private Set studentSubjectses = new HashSet(0);
     private Set paymentses = new HashSet(0);

    public AcademicClass() {
    }

    public AcademicClass(String className, Set studentRegistrations, Set teachers, Set studentses, Set subjectses, Set studentSubjectses, Set paymentses) {
       this.className = className;
       this.studentRegistrations = studentRegistrations;
       this.teachers = teachers;
       this.studentses = studentses;
       this.subjectses = subjectses;
       this.studentSubjectses = studentSubjectses;
       this.paymentses = paymentses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="class_name", length=45)
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="academicclass")
    public Set getStudentRegistrations() {
        return this.studentRegistrations;
    }
    
    public void setStudentRegistrations(Set studentRegistrations) {
        this.studentRegistrations = studentRegistrations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="academicclass")
    public Set getTeachers() {
        return this.teachers;
    }
    
    public void setTeachers(Set teachers) {
        this.teachers = teachers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="academicclass")
    public Set getStudentses() {
        return this.studentses;
    }
    
    public void setStudentses(Set studentses) {
        this.studentses = studentses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="academicclass")
    public Set getSubjectses() {
        return this.subjectses;
    }
    
    public void setSubjectses(Set subjectses) {
        this.subjectses = subjectses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="academicclass")
    public Set getStudentSubjectses() {
        return this.studentSubjectses;
    }
    
    public void setStudentSubjectses(Set studentSubjectses) {
        this.studentSubjectses = studentSubjectses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="academicclass")
    public Set getPaymentses() {
        return this.paymentses;
    }
    
    public void setPaymentses(Set paymentses) {
        this.paymentses = paymentses;
    }




}


