package com.inventory.system.model;
// Generated Jun 11, 2016 9:48:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Accounts generated by hbm2java
 */
@Entity
@Table(name="accounts"
    ,catalog="collegestudents"
    , uniqueConstraints = @UniqueConstraint(columnNames="account_number") 
)
public class Accounts  implements java.io.Serializable {


     private Integer id;
     private Students students;
     private String accountNumber;
     private String accountName;
     private String accountType;
     private Date dateCreated;
     private Set paymentses = new HashSet(0);

    public Accounts() {
    }

    public Accounts(Students students, String accountNumber, String accountName, String accountType, Date dateCreated, Set paymentses) {
       this.students = students;
       this.accountNumber = accountNumber;
       this.accountName = accountName;
       this.accountType = accountType;
       this.dateCreated = dateCreated;
       this.paymentses = paymentses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="students_id")
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }

    
    @Column(name="account_number", unique=true, length=45)
    public String getAccountNumber() {
        return this.accountNumber;
    }
    
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    
    @Column(name="account_name", length=45)
    public String getAccountName() {
        return this.accountName;
    }
    
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    
    @Column(name="account_type", length=45)
    public String getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="accounts")
    public Set getPaymentses() {
        return this.paymentses;
    }
    
    public void setPaymentses(Set paymentses) {
        this.paymentses = paymentses;
    }




}


