package com.inventory.system.model;
// Generated Jun 11, 2016 9:48:57 PM by Hibernate Tools 4.3.1


import com.inventory.system.support.InventoryHelper;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="collegestudents"
    , uniqueConstraints = @UniqueConstraint(columnNames="username") 
)
public class Admin extends InventoryHelper  implements java.io.Serializable {


     private Integer id;
     private NonTeachingStaff nonteachingstaff;
     private Teacher teacher;
     private String username;
     private String password;
     private String category;
     private Date dateCreated;
     private Set auditTrails = new HashSet(0);
     private Set messageses = new HashSet(0);
     private Set roles = new HashSet(0);

    public Admin() {
    }

    public Admin(NonTeachingStaff nonteachingstaff, Teacher teacher, String username, String password, String category, Date dateCreated, Set auditTrails, Set messageses, Set roles) {
       this.nonteachingstaff = nonteachingstaff;
       this.teacher = teacher;
       this.username = username;
       this.password = password;
       this.category = category;
       this.dateCreated = dateCreated;
       this.auditTrails = auditTrails;
       this.messageses = messageses;
       this.roles = roles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NonTeachingStaff_id")
    public NonTeachingStaff getNonteachingstaff() {
        return this.nonteachingstaff;
    }
    
    public void setNonteachingstaff(NonTeachingStaff nonteachingstaff) {
        this.nonteachingstaff = nonteachingstaff;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="teacher_id")
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

    
    @Column(name="username", unique=true, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", length=65535)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="category", length=45)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="admin")
    public Set getAuditTrails() {
        return this.auditTrails;
    }
    
    public void setAuditTrails(Set auditTrails) {
        this.auditTrails = auditTrails;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="admin")
    public Set getMessageses() {
        return this.messageses;
    }
    
    public void setMessageses(Set messageses) {
        this.messageses = messageses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="admin")
    public Set getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set roles) {
        this.roles = roles;
    }




}


