package com.inventory.system.model;
// Generated Jun 11, 2016 9:48:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuditTrail generated by hbm2java
 */
@Entity
@Table(name="audit_trail"
    ,catalog="collegestudents"
)
public class AuditTrail  implements java.io.Serializable {


     private Integer id;
     private Admin admin;
     private String source;
     private String actionPerformed;
     private String status;
     private Date trailDate;

    public AuditTrail() {
    }

    public AuditTrail(Admin admin, String source, String actionPerformed, String status, Date trailDate) {
       this.admin = admin;
       this.source = source;
       this.actionPerformed = actionPerformed;
       this.status = status;
       this.trailDate = trailDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin_id")
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    
    @Column(name="source", length=45)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

    
    @Column(name="action_performed", length=45)
    public String getActionPerformed() {
        return this.actionPerformed;
    }
    
    public void setActionPerformed(String actionPerformed) {
        this.actionPerformed = actionPerformed;
    }

    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="trail_date", length=19)
    public Date getTrailDate() {
        return this.trailDate;
    }
    
    public void setTrailDate(Date trailDate) {
        this.trailDate = trailDate;
    }




}


