package com.inventory.system.model;
// Generated Jun 11, 2016 9:48:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LocalGovernment generated by hbm2java
 */
@Entity
@Table(name="local_government"
    ,catalog="collegestudents"
)
public class LocalGovernment  implements java.io.Serializable {


     private Integer id;
     private State state;
     private String localGovernmentCode;
     private String localGovernmentName;
     private Set teachers = new HashSet(0);
     private Set nonteachingstaffs = new HashSet(0);

    public LocalGovernment() {
    }

    public LocalGovernment(State state, String localGovernmentCode, String localGovernmentName, Set teachers, Set nonteachingstaffs) {
       this.state = state;
       this.localGovernmentCode = localGovernmentCode;
       this.localGovernmentName = localGovernmentName;
       this.teachers = teachers;
       this.nonteachingstaffs = nonteachingstaffs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="state_id")
    public State getState() {
        return this.state;
    }
    
    public void setState(State state) {
        this.state = state;
    }

    
    @Column(name="local_government_code", length=45)
    public String getLocalGovernmentCode() {
        return this.localGovernmentCode;
    }
    
    public void setLocalGovernmentCode(String localGovernmentCode) {
        this.localGovernmentCode = localGovernmentCode;
    }

    
    @Column(name="local_government_name", length=100)
    public String getLocalGovernmentName() {
        return this.localGovernmentName;
    }
    
    public void setLocalGovernmentName(String localGovernmentName) {
        this.localGovernmentName = localGovernmentName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="localGovernment")
    public Set getTeachers() {
        return this.teachers;
    }
    
    public void setTeachers(Set teachers) {
        this.teachers = teachers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="localGovernment")
    public Set getNonteachingstaffs() {
        return this.nonteachingstaffs;
    }
    
    public void setNonteachingstaffs(Set nonteachingstaffs) {
        this.nonteachingstaffs = nonteachingstaffs;
    }




}


