package com.inventory.system.model;
// Generated Jun 11, 2016 9:48:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Messages generated by hbm2java
 */
@Entity
@Table(name="messages"
    ,catalog="collegestudents"
)
public class Messages  implements java.io.Serializable {


     private Integer id;
     private Admin admin;
     private String messageTitle;
     private String messageBody;
     private String messageStatus;
     private Date dateCreatde;

    public Messages() {
    }

    public Messages(Admin admin, String messageTitle, String messageBody, String messageStatus, Date dateCreatde) {
       this.admin = admin;
       this.messageTitle = messageTitle;
       this.messageBody = messageBody;
       this.messageStatus = messageStatus;
       this.dateCreatde = dateCreatde;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin_id")
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    
    @Column(name="message_title", length=45)
    public String getMessageTitle() {
        return this.messageTitle;
    }
    
    public void setMessageTitle(String messageTitle) {
        this.messageTitle = messageTitle;
    }

    
    @Column(name="message_body", length=45)
    public String getMessageBody() {
        return this.messageBody;
    }
    
    public void setMessageBody(String messageBody) {
        this.messageBody = messageBody;
    }

    
    @Column(name="message_status", length=45)
    public String getMessageStatus() {
        return this.messageStatus;
    }
    
    public void setMessageStatus(String messageStatus) {
        this.messageStatus = messageStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_creatde", length=19)
    public Date getDateCreatde() {
        return this.dateCreatde;
    }
    
    public void setDateCreatde(Date dateCreatde) {
        this.dateCreatde = dateCreatde;
    }




}


