package com.inventory.system.model;
// Generated Jun 11, 2016 9:48:57 PM by Hibernate Tools 4.3.1


import com.inventory.system.support.InventoryHelper;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 *NonTeachingStafff generated by hbm2java
 */
@Entity
@Table(name="nonteachingstaff"
    ,catalog="collegestudents"
    , uniqueConstraints = {@UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="phone_number"), @UniqueConstraint(columnNames="registration_number")} 
)
public class NonTeachingStaff  extends InventoryHelper implements java.io.Serializable {


     private Integer id;
     private LocalGovernment localGovernment;
     private String registrationNumber;
     private String title;
     private String firstName;
     private String middleName;
     private String lastName;
     private String email;
     private String phoneNumber;
     private Date registeredDate;
     private Date dateOfBirth;
     private String gender;
     private String placeOfBirth;
     private Set admins = new HashSet(0);

    public NonTeachingStaff() {
    }

    public NonTeachingStaff(LocalGovernment localGovernment, String registrationNumber, String title, 
            String firstName,String middleName, String lastName, String email, String phoneNumber, Date registeredDate, 
            Date dateOfBirth, String placeOfBirth, Set admins) {
       this.localGovernment = localGovernment;
       this.registrationNumber = registrationNumber;
       this.title = title;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.registeredDate = registeredDate;
       this.dateOfBirth = dateOfBirth;
       this.placeOfBirth = placeOfBirth;
       this.admins = admins;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="local_government_id")
    public LocalGovernment getLocalGovernment() {
        return this.localGovernment;
    }
    
    public void setLocalGovernment(LocalGovernment localGovernment) {
        this.localGovernment = localGovernment;
    }

    
    @Column(name="registration_number", unique=true, length=45)
    public String getRegistrationNumber() {
        return this.registrationNumber;
    }
    
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }

    
    @Column(name="title", length=45)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "first_name",length = 45)
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    
    @Column(name="middle_name", length=45)
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    @Column(name="last_name", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="email", unique=true, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone_number", unique=true, length=45)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Column(name="gender", length=45)
    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }        

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="registered_date", length=19)
    public Date getRegisteredDate() {
        return this.registeredDate;
    }
    
    public void setRegisteredDate(Date registeredDate) {
        this.registeredDate = registeredDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_of_birth", length=19)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    
    @Column(name="place_of_birth", length=45)
    public String getPlaceOfBirth() {
        return this.placeOfBirth;
    }
    
    public void setPlaceOfBirth(String placeOfBirth) {
        this.placeOfBirth = placeOfBirth;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nonteachingstaff")
    public Set getAdmins() {
        return this.admins;
    }
    
    public void setAdmins(Set admins) {
        this.admins = admins;
    }




}


