package com.inventory.system.model;
// Generated Jun 11, 2016 9:48:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payments generated by hbm2java
 */
@Entity
@Table(name="payments"
    ,catalog="collegestudents"
)
public class Payments  implements java.io.Serializable {


     private Integer id;
     private AcademicClass academicclass;
     private Accounts accounts;
     private BigDecimal amount;
     private String paymentReference;
     private Date paymentDate;
     private String academicSession;
     private String term;

    public Payments() {
    }

    public Payments (AcademicClass academicclass, Accounts accounts, BigDecimal amount, String paymentReference, Date paymentDate, String academicSession, String term) {
       this.academicclass = academicclass;
       this.accounts = accounts;
       this.amount = amount;
       this.paymentReference = paymentReference;
       this.paymentDate = paymentDate;
       this.academicSession = academicSession;
       this.term = term;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AcademicClass_id")
    public AcademicClass getAcademicclass() {
        return this.academicclass;
    }
    
    public void setAcademicclass(AcademicClass academicclass) {
        this.academicclass = academicclass;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="accounts_id")
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }

    
    @Column(name="amount")
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="payment_reference", length=45)
    public String getPaymentReference() {
        return this.paymentReference;
    }
    
    public void setPaymentReference(String paymentReference) {
        this.paymentReference = paymentReference;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="payment_date", length=19)
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    
    @Column(name="academic_session", length=100)
    public String getAcademicSession() {
        return this.academicSession;
    }
    
    public void setAcademicSession(String academicSession) {
        this.academicSession = academicSession;
    }

    
    @Column(name="term", length=45)
    public String getTerm() {
        return this.term;
    }
    
    public void setTerm(String term) {
        this.term = term;
    }




}


