package com.inventory.system.model;
// Generated Jun 11, 2016 9:48:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentSubjects generated by hbm2java
 */
@Entity
@Table(name="student_subjects"
    ,catalog="collegestudents"
)
public class StudentSubjects  implements java.io.Serializable {


     private StudentSubjectsId id;
     private AcademicClass academicclass;
     private Students students;
     private Subjects subjects;
     private Integer firstTestScore;
     private Integer secondTestScore;
     private Integer thirdTestScore;
     private Integer fourthTestScore;
     private Integer examScore;
     private Integer totalScore;
     private String percentage;
     private String session;
     private String term;
     private String remark;
     private Date dateCreated;

    public StudentSubjects() {
    }

	
    public StudentSubjects(StudentSubjectsId id, Students students, Subjects subjects) {
        this.id = id;
        this.students = students;
        this.subjects = subjects;
    }
    public StudentSubjects(StudentSubjectsId id,AcademicClass academicclass, Students students, Subjects subjects, Integer firstTestScore, Integer secondTestScore, Integer thirdTestScore, Integer fourthTestScore, Integer examScore, Integer totalScore, String percentage, String session, String term, String remark, Date dateCreated) {
       this.id = id;
       this.academicclass = academicclass;
       this.students = students;
       this.subjects = subjects;
       this.firstTestScore = firstTestScore;
       this.secondTestScore = secondTestScore;
       this.thirdTestScore = thirdTestScore;
       this.fourthTestScore = fourthTestScore;
       this.examScore = examScore;
       this.totalScore = totalScore;
       this.percentage = percentage;
       this.session = session;
       this.term = term;
       this.remark = remark;
       this.dateCreated = dateCreated;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="studentsId", column=@Column(name="students_id", nullable=false) ), 
        @AttributeOverride(name="subjectsId", column=@Column(name="subjects_id", nullable=false) ) } )
    public StudentSubjectsId getId() {
        return this.id;
    }
    
    public void setId(StudentSubjectsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AcademicClass_id")
    public AcademicClass getAcademicclass() {
        return this.academicclass;
    }
    
    public void setAcademicclass(AcademicClass academicclass) {
        this.academicclass = academicclass;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="students_id", nullable=false, insertable=false, updatable=false)
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="subjects_id", nullable=false, insertable=false, updatable=false)
    public Subjects getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Subjects subjects) {
        this.subjects = subjects;
    }

    
    @Column(name="first_test_score")
    public Integer getFirstTestScore() {
        return this.firstTestScore;
    }
    
    public void setFirstTestScore(Integer firstTestScore) {
        this.firstTestScore = firstTestScore;
    }

    
    @Column(name="second_test_score")
    public Integer getSecondTestScore() {
        return this.secondTestScore;
    }
    
    public void setSecondTestScore(Integer secondTestScore) {
        this.secondTestScore = secondTestScore;
    }

    
    @Column(name="third_test_score")
    public Integer getThirdTestScore() {
        return this.thirdTestScore;
    }
    
    public void setThirdTestScore(Integer thirdTestScore) {
        this.thirdTestScore = thirdTestScore;
    }

    
    @Column(name="fourth_test_score")
    public Integer getFourthTestScore() {
        return this.fourthTestScore;
    }
    
    public void setFourthTestScore(Integer fourthTestScore) {
        this.fourthTestScore = fourthTestScore;
    }

    
    @Column(name="exam_score")
    public Integer getExamScore() {
        return this.examScore;
    }
    
    public void setExamScore(Integer examScore) {
        this.examScore = examScore;
    }

    
    @Column(name="total_score")
    public Integer getTotalScore() {
        return this.totalScore;
    }
    
    public void setTotalScore(Integer totalScore) {
        this.totalScore = totalScore;
    }

    
    @Column(name="percentage", length=45)
    public String getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(String percentage) {
        this.percentage = percentage;
    }

    
    @Column(name="session", length=45)
    public String getSession() {
        return this.session;
    }
    
    public void setSession(String session) {
        this.session = session;
    }

    
    @Column(name="term", length=45)
    public String getTerm() {
        return this.term;
    }
    
    public void setTerm(String term) {
        this.term = term;
    }

    
    @Column(name="remark", length=45)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }




}


