package com.inventory.system.model;
// Generated Jun 11, 2016 9:48:57 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StudentSubjectsId generated by hbm2java
 */
@Embeddable
public class StudentSubjectsId  implements java.io.Serializable {


     private int studentsId;
     private int subjectsId;

    public StudentSubjectsId() {
    }

    public StudentSubjectsId(int studentsId, int subjectsId) {
       this.studentsId = studentsId;
       this.subjectsId = subjectsId;
    }
   


    @Column(name="students_id", nullable=false)
    public int getStudentsId() {
        return this.studentsId;
    }
    
    public void setStudentsId(int studentsId) {
        this.studentsId = studentsId;
    }


    @Column(name="subjects_id", nullable=false)
    public int getSubjectsId() {
        return this.subjectsId;
    }
    
    public void setSubjectsId(int subjectsId) {
        this.subjectsId = subjectsId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentSubjectsId) ) return false;
		 StudentSubjectsId castOther = ( StudentSubjectsId ) other; 
         
		 return (this.getStudentsId()==castOther.getStudentsId())
 && (this.getSubjectsId()==castOther.getSubjectsId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStudentsId();
         result = 37 * result + this.getSubjectsId();
         return result;
   }   


}


