package com.inventory.system.model;
// Generated Jun 11, 2016 9:48:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name="students"
    ,catalog="collegestudents"
)
public class Students  implements java.io.Serializable {


     private Integer id;
     private AcademicClass academicclass;
     private StudentRegistration studentRegistration;
     private String academicSession;
     private String academicTerm;
     private Date registeredDate;
     private Set accountses = new HashSet(0);
     private Set studentSubjectses = new HashSet(0);

    public Students() {
    }

    public Students(AcademicClass academicclass, StudentRegistration studentRegistration, String academicSession, String academicTerm, Date registeredDate, Set accountses, Set studentSubjectses) {
       this.academicclass = academicclass;
       this.studentRegistration = studentRegistration;
       this.academicSession = academicSession;
       this.academicTerm = academicTerm;
       this.registeredDate = registeredDate;
       this.accountses = accountses;
       this.studentSubjectses = studentSubjectses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AcademicClass_id")
    public AcademicClass getAcademicclass() {
        return this.academicclass;
    }
    
    public void setAcademicclass(AcademicClass academicclass) {
        this.academicclass = academicclass;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_registration_id")
    public StudentRegistration getStudentRegistration() {
        return this.studentRegistration;
    }
    
    public void setStudentRegistration(StudentRegistration studentRegistration) {
        this.studentRegistration = studentRegistration;
    }

    
    @Column(name="academic_session", length=45)
    public String getAcademicSession() {
        return this.academicSession;
    }
    
    public void setAcademicSession(String academicSession) {
        this.academicSession = academicSession;
    }

    
    @Column(name="academic_term", length=45)
    public String getAcademicTerm() {
        return this.academicTerm;
    }
    
    public void setAcademicTerm(String academicTerm) {
        this.academicTerm = academicTerm;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="registered_date", length=19)
    public Date getRegisteredDate() {
        return this.registeredDate;
    }
    
    public void setRegisteredDate(Date registeredDate) {
        this.registeredDate = registeredDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="students")
    public Set getAccountses() {
        return this.accountses;
    }
    
    public void setAccountses(Set accountses) {
        this.accountses = accountses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="students")
    public Set getStudentSubjectses() {
        return this.studentSubjectses;
    }
    
    public void setStudentSubjectses(Set studentSubjectses) {
        this.studentSubjectses = studentSubjectses;
    }




}


