package com.inventory.system.model;
// Generated Jun 11, 2016 9:48:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * StudentRegistration generated by hbm2java
 */
@Entity
@Table(name="student_registration"
    ,catalog="collegestudents"
    , uniqueConstraints = @UniqueConstraint(columnNames="registration_number") 
)
public class StudentRegistration  implements java.io.Serializable {


     private int id;
     private AcademicClass academicclass;
     private String registrationNumber;
     private String firstName;
     private String middleName;
     private String lastName;
     private String email;
     private String phoneNumber;
     private Date registeredDate;
     private Set studentses = new HashSet(0);
     private Set guidians = new HashSet(0);

    public StudentRegistration() {
    }

	
    public StudentRegistration(int id) {
        this.id = id;
    }
    public StudentRegistration(int id,AcademicClass academicclass, String registrationNumber, String firstName, String middleName, String lastName, String email, String phoneNumber, Date registeredDate, Set studentses, Set guidians) {
       this.id = id;
       this.academicclass = academicclass;
       this.registrationNumber = registrationNumber;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.registeredDate = registeredDate;
       this.studentses = studentses;
       this.guidians = guidians;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="academicclass_id")
    public AcademicClass getAcademicclass() {
        return this.academicclass;
    }
    
    public void setAcademicclass(AcademicClass academicclass) {
        this.academicclass = academicclass;
    }

    
    @Column(name="registration_number", unique=true, length=45)
    public String getRegistrationNumber() {
        return this.registrationNumber;
    }
    
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }

    
    @Column(name="first_name", length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="middle_name", length=45)
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    @Column(name="last_name", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone_number", length=45)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="registered_date", length=19)
    public Date getRegisteredDate() {
        return this.registeredDate;
    }
    
    public void setRegisteredDate(Date registeredDate) {
        this.registeredDate = registeredDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentRegistration")
    public Set getStudentses() {
        return this.studentses;
    }
    
    public void setStudentses(Set studentses) {
        this.studentses = studentses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentRegistration")
    public Set getGuidians() {
        return this.guidians;
    }
    
    public void setGuidians(Set guidians) {
        this.guidians = guidians;
    }




}


