package com.inventory.system.model;
// Generated Jun 11, 2016 9:48:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Subjects generated by hbm2java
 */
@Entity
@Table(name="subjects"
    ,catalog="collegestudents"
    , uniqueConstraints = @UniqueConstraint(columnNames="subject_code") 
)
public class Subjects  implements java.io.Serializable {


     private Integer id;
     private AcademicClass academicclass;
     private Teacher teacher;
     private String subjectCode;
     private String subjectName;
     private Date dateCreated;
     private Set studentSubjectses = new HashSet(0);

    public Subjects() {
    }

    public Subjects(AcademicClass academicclass, Teacher teacher, String subjectCode, String subjectName, Date dateCreated, Set studentSubjectses) {
       this.academicclass = academicclass;
       this.teacher = teacher;
       this.subjectCode = subjectCode;
       this.subjectName = subjectName;
       this.dateCreated = dateCreated;
       this.studentSubjectses = studentSubjectses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AcademicClass_id")
    public AcademicClass getAcademicclass() {
        return this.academicclass;
    }
    
    public void setAcademicclass(AcademicClass academicclass) {
        this.academicclass = academicclass;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="teacher_id")
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

    
    @Column(name="subject_code", unique=true, length=45)
    public String getSubjectCode() {
        return this.subjectCode;
    }
    
    public void setSubjectCode(String subjectCode) {
        this.subjectCode = subjectCode;
    }

    
    @Column(name="subject_name", length=45)
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subjects")
    public Set getStudentSubjectses() {
        return this.studentSubjectses;
    }
    
    public void setStudentSubjectses(Set studentSubjectses) {
        this.studentSubjectses = studentSubjectses;
    }




}


